name: Bug report form
about: Create a report to help improve the product
title: "[BUG] INSERT_BUG_NAME"
labels: bug
assignees: mathiskakal
projects: [algosup/29]
body:
  - type: markdown
    attributes:
      value: "**Expected behavior**\nA clear and concise description of what you expected to happen."
      
  - type: textarea
    id: expected-behavior
    attributes:
      label: Expected Behavior
      description: A clear and concise description of what you expected to happen.
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: "**Current Behavior**\nDescription of what is going on."
      
  - type: textarea
    id: current-behavior
    attributes:
      label: Current Behavior
      description: A detailed description of the current behavior.
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: "**To Reproduce**\nSteps to reproduce the behavior:"
      
  - type: textarea
    id: steps-to-reproduce
    attributes:
      label: Steps to Reproduce
      description: "Please provide steps to reproduce the issue:\n1. Go to '...'\n2. Click on '...'\n3. Scroll down to '...'\n4. See error"
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: |
        <details><summary><ins><em>Click to show template</em></ins></summary><br>
        
        \| Step ID \| Step Description \| Step Date \| Expected Results \| Actual Results \| Pass / Fail \| Add. Notes\|
        \|--------\|--------\|--------\|--------\|--------\|--------\|--------\|
        \| O \| Cell \| Cell \| Cell \| Cell \| Cell \| Cell \|
        \| 1 \| Cell \| Cell \| Cell \| Cell \| Cell \| Cell \|
        \| 2 \| Cell \| Cell \| Cell \| Cell \| Cell \| Cell \|
        
        </details>
        
  - type: markdown
    attributes:
      value: "**Screenshots**\nIf applicable, add screenshots to help explain your problem."
      
  - type: file
    id: screenshots
    attributes:
      label: Screenshots
      description: If applicable, add screenshots to help explain your problem.
      multiple: true
      
  - type: markdown
    attributes:
      value: "**Context (Environment in which the bug was produced):**"
      
  - type: input
    id: os
    attributes:
      label: Operating System
      description: The operating system you observed the bug on, e.g., iOS.
    validations:
      required: true
      
  - type: input
    id: browser
    attributes:
      label: Browser
      description: The browser in which you observed the bug, e.g., Chrome, Safari.
    validations:
      required: true
      
  - type: input
    id: version
    attributes:
      label: Version
      description: The version of the browser/OS where the bug was observed, e.g., 22.
    validations:
      required: true
      
  - type: markdown
    attributes:
      value: "**Additional context / Description**\nAdd any other context about the problem here."
      
  - type: textarea
    id: additional-context
    attributes:
      label: Additional Context / Description
      description: Add any other context about the problem here.
    validations:
      required: false
      
  - type: markdown
    attributes:
      value: "**Possible Implementation**\nDescribe suggestions for solving this issue."
      
  - type: textarea
    id: possible-implementation
    attributes:
      label: Possible Implementation
      description: Describe any suggestions for solving this issue.
    validations:
      required: false
