name: Hello world Workflow

on:
  push:
    branches:
      - actionsTests
  workflow_dispatch:

jobs:
  hello:
    runs-on: self-hosted
    steps:
      - uses: actions/checkout@v4.1.2
      - name: hello world
        run: echo "Hello World"
        shell: bash
  goodbye:
    runs-on: self-hosted
    steps:
      - name: goodbye world
        run: echo "Goodbye World"
        shell: bash
